### ISSUE TITLE
Support for managing Project Environment

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#164]
Hi there,

Does gitlabform has support for configuring/managing Project Environments? I skimmed through the code but didn't see any support for it. Thought I'd check in case I missed something. Below is the API docs from GitLab on Project Environments.

https://docs.gitlab.com/ee/api/environments.html

**Comment by gdubicki** [comment]
Hey @amimas !

No, we don't support this API yet. We are open to Pull Requests adding support for it. :)

**Comment by ss7548** [comment]
Please see pull request #190

**Comment by amimas** [comment]
PR #423 implemented ability to manage protected environment. Not sure if this should be considered as closed.

I guess regular environment config isn't available but maybe that's not a big deal or priority because those are created automatically through project's CI CD config (`.gitlab-ci.yml`). Only thing useful I can see for managing regular environments is to be able to delete envs that are not needed anymore; i.e. env created temporarily called review apps.

**Comment by gdubicki** [comment]
https://github.com/gitlabform/gitlabform/pull/423 has been released in [v3.3.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.3.0) today.

**Comment by kaihendry** [comment]
Be good if the [Feature matrix/comparison sheet](https://docs.google.com/spreadsheets/d/1RenC5OoLW_bt8QYrijNP42w8SGBw8JTg1-7RKWgStrQ/edit#gid=0) via https://gitlabform.github.io/gitlabform/similar_apps/ could be updated with support for Protected Environments. 😬

**Comment by amimas** [comment]
> I guess regular environment config isn't available but maybe that's not a big deal or priority because those are created automatically through project's CI CD config (.gitlab-ci.yml). Only thing useful I can see for managing regular environments is to be able to delete envs that are not needed anymore; i.e. env created temporarily called review apps.

Having gitlabform configure protected environments should be sufficient. Gitlab environments can be created by the CI config in a project when the pipeline runs. So there's not much to do for gitlabform. As for deleting those non protected environments as mentioned above, it might not be easy to decide because gitlabform can't know when an environment is in-use or not. Besides, gitlab CI already provides ability to stop environments from the CI pipeline.

Closing this issue for now. If there's other use cases, open a new issue with details.
