### ISSUE TITLE
Manage labels via gitlabform

### ISSUE THREAD

**Issue by FlorianLudwig** [gitlabform/gitlabform#168]
It would be nice to be able to manage labels within gitlabform, similar to how members can be managed.

This would add a new `labels` as well as `enforce_group_labels` and `enforce_project_labels` to the config.

Relevant API docs:
 * https://docs.gitlab.com/ee/api/labels.html
 * https://docs.gitlab.com/ee/api/group_labels.html

**Comment by gdubicki** [comment]
Hi @FlorianLudwig ! Thanks for the proposal. We are open to PRs with this feature. :)

**Comment by TimKnight-DWP** [comment]
https://python-gitlab.readthedocs.io/en/stable/gl_objects/labels.html

**Comment by amimas** [comment]
Implemented by #751 and available from release [v3.11.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.11.0)
