### ISSUE TITLE
Create non existent branches

### ISSUE THREAD

**Issue by twhiston** [gitlabform/gitlabform#20]
Does it make sense to add the ability to create branches in the tool?

I ask because we want to use it to keep our repo settings in line as people create repos in our namesapce, therefore the ideal flow would be:

repo created > hook fired > gitlabform run > master branch is created and branch protection enabled.

**Comment by gdubicki** [comment]
Hi @twhiston , sorry for a late reply!

I'll take a look at how much work would this require and get back to you.

We are of course open to getting PR with this too. Just let me know if you want to work on this so that we don't duplicate our efforts. :)

**Comment by twhiston** [comment]
Hi @gdubicki , thanks very much for the response, not sure that i have the bandwidth to work on this myself atm (sorry i know that sucks!), but if no one else has time in the New Year I might try to jump on it. If you do make an assessment of the effort required please do share it on here. The easiest way to deal with it manually is to commit some dummy file content with the api so that the branch can be created (a generic readme in this case), so that is how we are working around it currently before calling gitlabform to apply the settings that we need.

Thanks for an awesome tool!

**Comment by lukasmrtvy** [comment]
Should be possible via https://docs.gitlab.com/ee/api/branches.html#create-repository-branch api endpoint, would be nice to implement this in gitlabform.

**Comment by twhiston** [comment]
I don't work as an engineer any more, so I have no stake in this feature now I'm afraid.

**Comment by amimas** [comment]
@gdubicki - should we close this issue since there aren't any activity and not many are looking for this feature.

**Comment by gdubicki** [comment]
Closing, but if anyone wants to pick this up again, feel free!
