### ISSUE TITLE
Support multiple Merge Request approval rules

### ISSUE THREAD

**Issue by Mahpara93** [gitlabform/gitlabform#263]
Is there a way we could have multiple approval rules added using gitlabform? https://docs.gitlab.com/ee/user/project/merge_requests/approvals/rules.html#add-multiple-approval-rules

Thanks,

Mahpara

**Comment by Mahpara93** [comment]
Looks like something that's already in the works https://github.com/egnyte/gitlabform/pull/176. Closing this issue.

**Comment by gdubicki** [comment]
Nvm, sorry. Please see #388 for further work on this.
