### ISSUE TITLE
bug:  {'private-token': 'token'} must be of type str or bytes

### ISSUE THREAD

**Issue by oliverbaehler** [gitlabform/gitlabform#401]
**Describe the bug**

I tried gitlabform today for the first (awesome project). I noticed that i get the following error (That's when i test it locally):

```
 gitlabform --config config.yml ALL_DEFINED
🏗  GitLabForm version: 3.0.0.post1 = the latest stable 😊
Error: GitLab test request failed:
Header part ('token') from {'private-token': 'token'} must be of type str or bytes, not <class 'ruamel.yaml.scalarstring.DoubleQuotedScalarString'>
```

And with the latest container build:

```
$ docker run -it -v $(pwd):/config ghcr.io/gitlabform/gitlabform:latest gitlabform ALL_DEFINED

🏗  GitLabForm version: 3.0.0 = outdated 😔, please update! (the latest stable is 3.0.0.post1)
Error: GitLab test request failed:
Header part ('token') from {'private-token': 'token'} must be of type str or bytes, not <class 'ruamel.yaml.scalarstring.DoubleQuotedScalarString'>
```
So i guess that eliminates client stuff. Am a just a bit too naive or is this an actual bug? If you can confirm its a bug i would liek to open a pr.  

However if i just define them as envs (unset in config), i come further in the process:

```
docker run -it -v $(pwd):/config -e GITLAB_URL=https://git.company.com -e GITLAB_TOKEN=tokenghcr.io/gitlabform/gitlabform:3.0.0.post1 gitlabform ALL_DEFINED

🏗  GitLabForm version: 3.0.0.post1 = the latest stable 😊
Error: GitLab test request failed:
HTTPSConnectionPool(host='git.company.com', port=443): Max retries exceeded with url: /api/v4/version?per_page=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffa3908f10>, 'Connection to git.company.com timed out. (connect timeout=10)'))
```

(Timeout is alright, it's not public reachable)

The Config looks like this:

```
# Reference
config_version: 3

# GitLab API access config
gitlab:
  # alternatively use the GITLAB_URL environment variable for this
  url: "https://git.company.com"
  # alternatively use the GITLAB_TOKEN environment variable for this#
  token: "token"
```
**GitLabForm version**

`🏗  GitLabForm version: 3.0.0.post1 = the latest stable 😊`

**GitLab version**

F.e. `13.12.4-ee`

**Comment by gdubicki** [comment]
Hi @oliverbaehler! Thanks for your kind words and for reporting the bug.

For now I was able to reproduce it - if you single or double-quote the token then you get the error. Do you already know what is causing it, if you propose to create a PR? (Which is, of course, very welcome.)

**Comment by oliverbaehler** [comment]
@gdubicki No but i will take the time to look into it. I guess some sort of string conversion will be enough

**Comment by amimas** [comment]
In terms of best practices or security, the token should be provided as a CLI parameter or environment variable.

Should we perhaps consider removing support for adding token directly in the config file starting next major release? That way no fix is needed. What're the use case of providing token in the config file directly?

**Comment by gdubicki** [comment]
I think that there are valid use cases when the token can be provided in the configuration file and I would not remove this feature, @amimas.

For example, we keep all the secrets, including the token, encrypted within the config using [hiera-eyaml](https://github.com/voxpupuli/hiera-eyaml) and only when the config is used it's being temporarily deployed on a short-lived compute instance in an unencrypted form.

**Comment by oliverbaehler** [comment]
@gdubicki Do you guys have a slack or something where you talk about the development of this project, i would love to help maintain this project.

I agree, we should leave the key in the config. What if we allow environment substitution in the config. This seems interesting for different use cases:

```
...
gitlab:
  url: "${CI_SERVER_URL}"
  # alternatively use the GITLAB_TOKEN environment variable
  token: "${ENV_SUBST}"
```

**Comment by gdubicki** [comment]
Sure @oliverbaehler, please join us on our Slack here: https://join.slack.com/t/gitlabform/shared_invite/zt-1ex8gk35t-gSFIWngE4EamEe7WE9RhhQ

**Comment by gdubicki** [comment]
Release [v4.1.1 ](https://github.com/gitlabform/gitlabform/releases/tag/v3.1.1) should have this fixed. Please reopen if you see any more issues, @oliverbaehler.

**Comment by RajasGujarathi** [comment]
> Sure @oliverbaehler, please join us on our Slack here: https://join.slack.com/t/gitlabform/shared_invite/zt-1ex8gk35t-gSFIWngE4EamEe7WE9RhhQ

I wish to join the community but I do not have an email ending with `epfl.ch`. Can someone help me with an invite, please?

**Comment by gdubicki** [comment]
@RajasGujarathi: please try using this invite link: https://join.slack.com/t/gitlabform/shared_invite/zt-1sav7j5g5-zocazuAKiZALtun_uzYo_w

**Comment by RajasGujarathi** [comment]
Thanks @gdubicki
