### ISSUE TITLE
Evenly distribute load of scheduled pipelines by variable cron expressions

### ISSUE THREAD

**Issue by pho3nixx** [gitlabform/gitlabform#455]
When configuring schedules via GitLabForm for a larger number of projects using wildcards at `projects_and_groups`, all generated pipeline schedules share the exact same cron expression. When these pipelines get triggered, it puts heavy load on the Gitlab-CI runners due to all pipelines running simultaneously.

To distribute the load over time, one could configure every project's pipeline schedule cron pattern individually, which is cumbersome and in part against what GitLabForm strives for: managing multiple projects with minimal work.

Looking at good old Jenkins CI, they offer a variable `H` ("hash") to be used within the cron expression to achieve a random equal distribution of e.g. daily/nightly jobs: https://www.jenkins.io/doc/book/pipeline/syntax/#cron-syntax

It would be very helpful, if the same or a similar mechanism was available in GitLabForm.

**Comment by gdubicki** [comment]
Hi @pho3nixx! Thanks for the suggestion.

A complete implementation of this seems quite difficult to be done right, see https://gitlab.com/gitlab-org/gitlab/-/issues/17799. But perhaps this is also the reason that issue in GitLab is open for more than 5 years now...

So a simpler solution to automate replacing `H`s with a random value from the appropriate range based on a seed from the group/project name (+ maybe the schedule name?) seems not that hard and could be done in GitLabForm.

If you or someone else would provide a working implementation of this feature in a PR, we will definitely review it and if it works, merge it.

**Comment by mfriedenhagen** [comment]
Hi @gdubicki I think my MR is now ready to be reviewed, it would be nice if you could take a look :-)

**Comment by gdubicki** [comment]
Thank you again for contributing your implementation, @mfriedenhagen! 😊 Released in [v3.14.1](https://github.com/gitlabform/gitlabform/releases/tag/v3.14.1) a moment ago. 🎊
