### ISSUE TITLE
Add troubleshooting infos

### ISSUE THREAD

**Issue by guilhem-martin** [gitlabform/gitlabform#462]
When we get an error, like ":: # of projects failed: 3", we get a list of failed project applications:

`":: Failed project 6: <name of project>"`

Is there a way to have the details (reason, error message, ...) of the failure? 

Thanks.

**Comment by gdubicki** [comment]
Hi @guilhem-martin! This is just a summary that tells you to check the output above for the mention about the given project and the detailed error message. Aren't you seeing it above in the output? What verbosity level are you using? (normal, `-v`erbose, `-d`ebug?)

**Comment by gdubicki** [comment]
Hey @guilhem-martin, did you see my questions above?

**Comment by guilhem-martin** [comment]
Sorry for the late reply.
Thanks a lot @gdubicki for the helpful answer.

**Comment by gdubicki** [comment]
👍
