### ISSUE TITLE
Protecting environment using group name returns error

### ISSUE THREAD

**Issue by long-wan-ep** [gitlabform/gitlabform#503]
**Describe the bug**

When trying to protect an environment using `group` with group name (https://gitlabform.github.io/gitlabform/reference/protected_environments/), the GitLab API returns the error `Deploy access levels is too short (minimum is 1 character)`. Seems like the API does not support `group`(https://docs.gitlab.com/ee/api/protected_environments.html#protect-a-single-environment), switching to `group_id` worked.

**GitLabForm version**
3.4.1

**GitLab version**
15.7.7-ee

**Comment by gdubicki** [comment]
Thanks for reporting this @long-wan-ep! It's true, we missed adding the support for group names when we implemented this feature and we didn't notice because we didn't have a test for that.

Both of these should be fixed in the linked PR.

**Comment by gdubicki** [comment]
Released in [v3.4.3](https://github.com/gitlabform/gitlabform/releases/tag/v3.4.3).

**Comment by amimas** [comment]
Thanks for the quick fix @gdubicki. We'll try it out soon.
