### ISSUE TITLE
Add `allowed_to_create` support for tag protection

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#505]
Currently gitlabform can be used for branch protection with additional options of `allowed_to_merge` and `allowed_to_push`.

Gitlab has similar option for protected tags named `allowed_to_create` but looks like that can't be configured using gitlabform at the moment. Tag protection is only configurable using  `create_access_level`.

This would be useful for protecting tags that are created by release bots only or by specific users.

**Comment by gdubicki** [comment]
Hi @amimas! I confirm that the current code supports only `create_access_level`, but it should be easy to extend it to support `allowed_to_create` too. PR are welcome!

**Comment by amimas** [comment]
This is now available in v3.8.0: https://github.com/gitlabform/gitlabform/releases/tag/v3.8.0
