### ISSUE TITLE
Unexpected missing approvals_before_merge warnings

### ISSUE THREAD

**Issue by vchepkov** [gitlabform/gitlabform#514]
**Describe the bug**

After converting config file to new merge_requests_approval_rules format, I see multiple warnings, like this
```
Warning: 'approvals_before_merge' not found in the old 'merge_requests' configuration section - assuming that it is set to 2.
```
Unfortunately, gitlabform doesn't report, which section has issues and running it in debug mode didn't help either.

**GitLabForm version**

$ gitlabform -V
🏗 GitLabForm version: 3.4.3 = the latest stable 😊

**GitLab version**

15.6.8-ee

**Comment by gdubicki** [comment]
Hey!

Yes, I am aware of those deprecation messages deficiencies... Sadly I don't have the time to improve them to show the exact place in the config where the issue occurs.

But you can find those places with some regexp search within your config.

For example, I have tried this regexp `merge_requests:((.|\n)*?)approvals_before_merge:` and it has shown me the places where I have the issue - see the code pointed by the red arrow in the below screenshot:

<img width="691" alt="Screenshot 2023-03-13 at 17 31 08" src="https://user-images.githubusercontent.com/566632/224782200-4a596cdc-e296-4266-9bf1-d7976342d8fa.png">

**Comment by vchepkov** [comment]
I found them thank you, we can close this ticket
I will submit another one when I decide if that is a bug or a feature :)
