### ISSUE TITLE
Breaking Inheritance

### ISSUE THREAD

**Issue by felsgaertner** [gitlabform/gitlabform#537]
Hello, 

the example in https://github.com/gitlabform/gitlabform/blob/main/docs/reference/index.md#breaking-inheritance states that key_a will be deployed.

I would expect key_b to be deployed. Why else should I break the inheritance? For me, breaking inheritance means to *not* have key_a in my project.

**Comment by amimas** [comment]
I believe you're right. It looks like a docs typo.

**Comment by felsgaertner** [comment]
Thanks for your check, but what is implemented in the code?

**Comment by RajasGujarathi** [comment]
#536 should fix the documentation (_I realised and tested this feature earlier this week_)

The behaviour works as expected, just the documentation needs an update.

**Comment by gdubicki** [comment]
Thanks for reporting the issue, @felsgaertner! Documentation is fixed now with @RajasGujarathi's PR. 👍
