### ISSUE TITLE
Usernames in projects and groups should be case-insensitive

### ISSUE THREAD

**Issue by J4Numbers** [gitlabform/gitlabform#555]
# Background

Currently, a username in GitLab will resolve down to an ID at some level. That username exists as a namespace in front of the ID number and is case-insensitive when querying the [GitLab list users API](https://docs.gitlab.com/ee/api/users.html#list-users) about it.

## Existing behaviour

(As seen on `3.6.0`)

Given that `Joe.Bloggs` already exists as a member of a group,

When running a configuration which includes a username of `joe.bloggs` against that group,

Then the GitLabForm attempts to add `joe.bloggs` to that group,

And the GitLabForm fails, stating that the ID number of `Joe.Bloggs` already exists against that group.

## Proposed behaviour

Given that `Joe.Bloggs` already exists as a member of a group,

When running a configuration which includes a username of `joe.bloggs` against that group,

Then the GitLabForm does not attempt to add the existing member to that group.

**Comment by gdubicki** [comment]
Hi, @J4Numbers, thanks for reporting the issue.

It's a known one though, discovered in https://github.com/gitlabform/gitlabform/issues/466 and some time ago I started working on a fix but I only found the time to implement tests that show that for now the names are treated as case-sensitive: https://github.com/gitlabform/gitlabform/pull/475

Sadly I still have little time so if you or someone else needs this badly, you can feel free to take over my PR (or start from the scratch, if you prefer) and implement it. Some day I might complete it myself, but I cannot tell you when, sorry.

**Comment by amimas** [comment]
This is now available in v3.8.0: https://github.com/gitlabform/gitlabform/releases/tag/v3.8.0
