### ISSUE TITLE
Gitlab 16.x: cannot update settings of archived projects

### ISSUE THREAD

**Issue by admantium-sg** [gitlabform/gitlabform#578]
**Describe the bug**

Hello, we recently updated from Gitlab 15.X to 16.0.7. 

The gitlab-form run worked flawlessly with 15.x, but in 16 we see an error when processing archived projects. Non-Archived projects are processed successfully.

**GitLabForm version**

`GitLabForm version: 3.7.0 = the latest stable 😊`

**GitLab version**

`16.0.7-ee`

**GitLabForm Config**

Excerpt

```
config_version: 3

projects_and_groups:
  "*":
    project_settings:
      visibility: private
      remove_source_branch_after_merge: true
    branches:
      develop:
        protected: true
        push_access_level: developer
        merge_access_level: developer
      master:
        protected: true
        push_access_level: no access
        merge_access_level: maintainer
      main:
        protected: true
        push_access_level: no access
        merge_access_level: maintainer
     ...
```

**GitLabForm Log Output**

Excerpt

```
/usr/local/bin/gitlabform --include-archived-projects --verbose ALL
🏗 GitLabForm version: 3.7.0 = the latest stable 😊
Reading config from file: config.yml
Connected to GitLab version: 16.0.7-ee (5ed4b9a2beb)
Connected as: root, admin: yes
>>> Getting ALL groups and projects that I have permission to modify...
...
projects: ['archive/react-redux-boilerplate', ...
...
* (  1/522) Processing project: archive/react-redux-boilerplate
Skipping section 'project' - not in config.
Processing section 'project_settings'
Editing project_settings in archive/react-redux-boilerplate
Skipping section 'project_push_rules' - not in config.
Skipping section 'deploy_keys' - not in config.
Skipping section 'variables' - not in config.
Processing section 'branches'
Warning: Error occurred while processing project archive/react-redux-boilerplate, exception:

Request url='https://our.private.url/api/v4/projects/archive%2Freact-redux-boilerplate/protected_branches/develop', method=DELETE, failed - expected code(s) [200, 201, 204, 404], got code 403 & body: '{"message":"403 Forbidden"}'
```

**Comment by admantium-sg** [comment]
Hello @amimas,

thanks for checking this.

The full configuration of the `branches` section is updated in the ticket description.

I was also wondering about the `DELETE` request.  Is there a way to run gitlabform in debug mode and see the details of its requests to the GitLab API?

**Comment by amimas** [comment]
> Is there a way to run gitlabform in debug mode and see the details of its requests to the GitLab API?

You can run gitlabform with `--debug` option. It's going to be ton of log though. Maybe recreate the issue in another group that has couple of projects including an archived project.

> The full configuration of the branches section is updated in the ticket description.

Thanks! I don't see anything wrong on the surface. Admittedly I also don't use the `--include-archived-projects` option in my workflow so far because once a project is archived, there's no need to keep maintaining it's settings. The project is going to be in "read-only" mode anyways. So, I'm not actually sure how this option works.

I assume you used the same version of `gitlabform` between GitLab 15.x and 16.x, is that right? I believe right now gitlabform processes branch protection by removing existing protection and then adding the protection according to the config. That's why it makes sense to me that there's a `DELETE` request. But what's puzzling me is that you're saying things worked as is with GitLab 15.x.

Double checking... are you sure there aren't any other changes? :)

**Comment by amimas** [comment]
> The only other change: on encountering the error, I update from gitlabform 3.6.0 to 3.7.0.

I don't see any related changes in that version update that would've broken it. Are you able to try version `3.6.0` and see if it works?

I also couldn't find any reference in GitLab's docs or their feature deprecation lists that mentions updating branch protection setting of an already archived project is doable or has changed in version 16.x. So, I'm still surprised that this worked in Gitlab version 15.x.

Maybe @gdubicki  or others might be able to chime in.

Just out of curiosity though, what's the reason you're running gitlabform with `--include-archived-projects` parameter if the intention is to not "unarchive" those projects?

**Comment by admantium-sg** [comment]
`3.6.0` did not work, that why I upgraded.

We want to apply the same ruleset to all projects. A person with access to Gitlab could manually unarchive a repo, change its visibility etc, then archive it. I we can not change the archived project, it retains its not intend settings.

Another idea: Can we run gitlabform such that it only runs on archived projects, then change its settings, then archive them again?

**Comment by amimas** [comment]
> We want to apply the same ruleset to all projects.

I think this goes back to the initial issue. Archived projects are read-only and your ruleset/config can change anytime or as gitlab releases new feature to project settings/configs. So, those cannot be applied on an archived (aka. read-only) project. Unless gitlabform processes archived project the way you've proposed.

> Can we run gitlabform such that it only runs on archived projects, unarchive and change its settings, then archive them again?

I guess in addition to `--include-archived-projects` parameter, we might need another parameter named `--update-archived-projects` that will do what you've proposed above. PR for this is welcome :)

A work-around I can think of is to run gitlabform multiple times. For example:

- Update config of archived projects to replace `archived: true` to `archived: false` (i.e. using `sed` or other commands)
- Run `gitlabform` using `--include-archived-projects` parameter
- Re-do step 1 above to set the projects to `archived: true` again
- Run `gitlabform`

**Comment by admantium-sg** [comment]
Hello @amimas,

thanks for the workflow suggestion, and the nudge to provide a PR to gitlabform. I can not promise to work on it, but its in my mind :) 

You can close this issue.

**Comment by amimas** [comment]
I did some test using Gitlab 15.11.13 docker image and 16.2.2 (latest). Created 2 projects using the UI (`project1`, and `project-archived`) and it just had the default branch protection out of the box. Used your sample config with gitlabform version 3.7.0 for both versions of Gitlab.

It worked fine in Gitlab v15 but failed in Gitlab v16. Error was similar to yours. So, I'm leaning towards something changed in Gitlab as a breaking change but it's not documented (at least I couldn't find it).

Also, looks like the archived projects can still be processed (i.e. project settings) using gitlabform 3.7.0 with GitLab v16. Didn't check other type of changes but at least branch protection processing seems to not work for archived projects.

I tried the branch protection on an archived project in Gitlab v16 using [gitlab's protected branch api docs](https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches) (using the sample command from there). That also fails with same error message.

```shell
$ curl --request POST --header "PRIVATE-TOKEN: token-string-here123" "http://localhost/api/v4/projects/2/protected_branches?name=*-stable&push_access_level=30&merge_access_level=30&unprotect_access_level=40"
{"message":"403 Forbidden"}
```

I'm pretty sure it's a Gitlab bug but didn't find an open issue.

**Comment by gdubicki** [comment]
> (but not running latest gitlabform because of some other open issues).

What issues are blocking you, @bitlord? Maybe we can speed up fixing them.

**Comment by amimas** [comment]
I recently ran into similar issue. It's not just isolated to branch protection setting while the project is archived. My config for the project was like this:

```yaml
group1/project-foo:
  project:
    archived: true
  project_settings:
    description: ... # updated the description to refer to another project/tool that replaced this.
    .... # other settings here
```

When gitlabform ran, it archived the project but didn't update the description. There wasn't any errors and didn't have any other useful logs either because I typically don't run gitlabform with `--debug` or `--verbose` to avoid noise.

I'm running gitlabform v3.7.0 with gitlab version 16.1.x.

I later manually updated the description of the project. So, gitlab still allows updating project's settings, but the API doesn't seem to do that.

**Comment by amimas** [comment]
@admantium-sg , Are you able to test it out using latest version of gitlab? Wondering if the API behaviour changed/fixed in newer version of gitlab.

Anyways, going to close this issue since it's not a gitlabform bug. Feel free to reopen if you find the issue to be in gitlabform.
