### ISSUE TITLE
Support `job_token_scope` configuration

### ISSUE THREAD

**Issue by hertzsprung** [gitlabform/gitlabform#607]
GitLab provides a [`PATCH` request to enable or disable a project's `job_token_scope`](https://docs.gitlab.com/ee/api/project_job_token_scopes.html#patch-a-projects-cicd-job-token-access-settings).
But, as far as I'm aware, this is not yet supported by gitlabform.

**Comment by hertzsprung** [comment]
It's closely related, feel free to combine the two issues if appropriate. But the PATCH request only sets a boolean flag for the project, it doesn't allow fine grained control provided by the allowlist.

**Comment by amimas** [comment]
> the PATCH request only sets a boolean flag for the project, 

Thanks for clarifying. I think it's fine for this to be a separate issue. Can be implemented without everything related to job token being involved. Keeps the scope small.

PRs are welcome. Would you be able to help contribute this feature? Do you have a proposal for the config syntax?

**Comment by hertzsprung** [comment]
Makes sense, thanks.  I'll get back to you next week with a config syntax proposal that accommodates #607 and #571.  If we're happy I'll try to find time to contribute, too.

**Comment by amimas** [comment]
That sounds great!! Thanks.

**Comment by amimas** [comment]
This has been completed and released in [v3.12.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.12.0).
