### ISSUE TITLE
Migrate `integrations` feature to use python-gitlab library

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#623]
Goal of this issue is to migrate the `integrations` configuration feature to use [python-gitlab library](https://python-gitlab.readthedocs.io/en/stable/) instead of using homegrown API in this project.

Todo:

- Delete `gitlabform/gitlab/integrations.py` as it shouldn't be needed anymore
- Update `gitlabform/processors/project/integrations_processor.py`
  - To use the `python-gitlab` library, use `self.gl` instead of `self.gitlab`. See the library docs for more help

**Comment by nabinbhatt** [comment]
@amimas can it get assigned to me?

**Comment by amimas** [comment]
Sure @nabinbhatt . Welcome and thank you for helping.

**Comment by amimas** [comment]
@nabinbhatt - were you able to make any progress with this?
