### ISSUE TITLE
Add `enforce` support for `hooks` configuration

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#662]
In `hooks` configuration, the target url is used as the key for each hook with additional properties under it. If the hook is removed or the url is changed, the one that was previously created/updated will still remain in the gitlab project. It'd be great to add `enforce: true` support for `hooks` similar to other configs that supports the same enforce key. If a hook is not in the gitlabform configuration, it will be deleted. This helps to keep project's state in sync with config-as-code.

**Comment by TigreModerata** [comment]
Hi, I'd like to give this a try (I should be familiar with hooks management now ;) )

**Comment by amimas** [comment]
Thanks @TigreModerata for willing to contribute. Please feel free to pick this up when you can. PRs are welcome.

**Comment by amimas** [comment]
This is now available in [v3.9.0 release](https://github.com/gitlabform/gitlabform/releases/tag/v3.9.0). Thanks for your contribution.
