### ISSUE TITLE
Is there a way to manage CI/CD settings at project level for "Keep artifacts from most recent successful jobs" using gitlab forms.

### ISSUE THREAD

**Issue by pavankunadaharaju** [gitlabform/gitlabform#678]
Write whatever you like :)
Is there a way to manage CI/CD settings at the project level for "Keep artifacts from most recent successful jobs" using Gitlab forms.

I wanted to manage the below configuration using gitlabforms

![image](https://github.com/gitlabform/gitlabform/assets/26820504/3d6fa462-a992-493a-b053-b6e8318baef9)

**Comment by amimas** [comment]
That option is part of project settings api: https://docs.gitlab.com/ee/api/projects.html#edit-project

You should be able to manage it by enable or disable the `keep_latest_artifact` attribute.

**Comment by amimas** [comment]
Were you able to manage the setting as mentioned above?

**Comment by amimas** [comment]
Closing this issue. Feel free to reopen if needed.
