### ISSUE TITLE
Transfer project does not work when gitlabform run with ALL_DEFINED or ALL as the target

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#689]
**Describe the bug**

Version 3.9.0 added a feature for transferring a project from one namespace to another. But it only seems to work when `gitlabform` is run with the project being the direct target. Consider following config sample:

```yaml
# test-config.yml

config_version: 3

projects_and_groups:
  group-bar/project-transfer-test:
    project:
        transfer_from: group-foo/project-transfer-test
```

If we run `gitlabform --config test-config.yml group-bar/project-transfer-test`, the above config is processed successfully and the project gets transferred from `group-foo/project-transfer-test` to `group-bar/project-transfer-test`. The dry-run (`--noop`) also seems to complete without errors.

But, if we run `gitlabform --config test-config.yml ALL_DEFINED` following error is returned:

```
Error: Configuration contains project group-bar/project-transfer-test but it cannot be found in GitLab!
```

 If we run `gitlabform --config test-config.yml ALL` (with or without `--noop`), following message is returned indicating there's nothing to do. Running `gitlabform --config test-config.yml group-bar` (using group name as the target), produces same result.

```
🏗 GitLabForm version: 3.9.0 = the latest stable 😊
>>> Getting ALL groups and projects that I have permission to modify...
:: # of groups to process: 0
:: (# of omitted groups - empty effective config: 2)
:: # of projects to process: 0
:: (# of omitted projects - empty effective config: 1)
:: Nothing to do. 
```

**GitLabForm version**

Output of `gitlabform -V`

🏗 GitLabForm version: 3.9.0 = the latest stable 😊

**GitLab version**

F.e. `16.8.2-ee`

**Comment by long-wan-ep** [comment]
My team is also running into this, I can take a stab at it.
