### ISSUE TITLE
CI/CD settings: Whitelist project for Token Access

### ISSUE THREAD

**Issue by tintilux** [gitlabform/gitlabform#716]
Is there a way to configure the whitelist for Projects, which should have access?
<img width="895" alt="Bildschirmfoto 2024-03-28 um 15 07 59" src="https://github.com/gitlabform/gitlabform/assets/63294551/613d219a-4e46-4223-935e-0fe162eafce0">

**Comment by amimas** [comment]
It's not supported yet. It's being worked on though. Please follow issue #571 for progress or updates. Check in there if you can lend a hand with that. I'm going to close this since it's a duplicate issue.
