### ISSUE TITLE
Drop python < 3.12

### ISSUE THREAD

**Issue by TimKnight-DWP** [gitlabform/gitlabform#754]
3.8 EOL 10-2024
3.9 EOL 10-2025

We will need to drop them anyway by the above dates

If we dropped these earlier we could support `Obj | Obj` typing for example `Group | Project` which is going to become more and more useful as we adopt python-gitlab.

**Comment by amimas** [comment]
> we could support a secondary release branch for hot fixes to the previous major version

Personally I'd avoid multiple version support. It'll bring additional maintenance that I think we don't need or can afford.

**Comment by gdubicki** [comment]
I wanted to share with others who might be reading this issue that we discussed this within the maintainers team and agreed to stop supporting all version of Python except the latest stable.

The benefits would be:
* enabling new syntax for optimal development experience,
* less tests to run - less chance of running into flakiness, lower CI/CD use which could help if we move to GitLab and GitLab CI, lower resource use is better for the environment 🌱
* optimal performance as new Python versions are faster (but it's not a very significant factor in our case),

The downsides:
* some users will have to switch to run the app with Docker if they are stuck with old Python but a) [the switch is easy](https://gitlabform.github.io/gitlabform/installation/#run-without-installing), b) they will have to switch or upgrade Python at some point anyway,
* we may alienate some potential contributors who are stuck with old Python on their dev envs? - not sure if that’s really a realistic scenario, is anyone really using something like Centos 7 or Ubunto 18.04 on a desktop?

If anyone has anything to add here, in particular something that would make us change our minds, please share your thoughts!
