### ISSUE TITLE
GitLab 17.0 Issues

### ISSUE THREAD

**Issue by TimKnight-DWP** [gitlabform/gitlabform#764]
**Describe the bug**

Issue to track issues when running GLF vs GitLab 17.0 (release 16/05/24)

**GitLabForm version**

3.11.1

**GitLab version**

17.0.0-ee

**Comment by TimKnight-DWP** [comment]
**test_schedules.py** -> Is now failing on all branches, suggesting something within Schedules has changed in 17.*

**Comment by amimas** [comment]
@TimKnight-DWP - Do we still need to keep this issue open? If not, let's close it. Also, looks like this was specifically around scheduled pipeline related changes, which has been addressed by above PR? If yes, would be good to update the title and description of this issue for future references.

**Comment by TimKnight-DWP** [comment]
@amimas no I think this was fixed?

Closing now
