### ISSUE TITLE
Within the documentation site, the configuration link to "Group SAML links" page is missing on the left panel

### ISSUE THREAD

**Issue by fbarutel** [gitlabform/gitlabform#782]
**Describe the bug**
The link to "Group SAML links" page is missing when you develop the "Configuration" list on the left frame of the [documentation site](https://gitlabform.github.io/gitlabform/).
Nevertheless, the target page which url seems to be https://gitlabform.github.io/gitlabform/reference/group_saml_links/ exists.

**GitLabForm version**

Among release notes "Group SAML links" was introduced recently in released version [3.12.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.12.0)

**GitLab version**

N/A

**Note**
By the way, many thanks about the implementation of "Group SAML links" which I'm going to use it within GitLab.com instance.

**Comment by fbarutel** [comment]
Hello,
On GitLabForm web site https://gitlabform.github.io/gitlabform/, I still cannot see the entry "Group SAML links" in the sublist of "Configuration" entry. And sadly, it isn't a cache issue from my browser.
So, I'm sorry but this issue isn't solved yet.

**Comment by amimas** [comment]
The docs site config had been updated in the PR that closed it but looks like the GitHub action only has logic to build the docs site; doesn't actually publish it, if I'm not mistaken 😞.

**Comment by amimas** [comment]
It seems, the link on the docs site has been fixed.

<img width="616" alt="image" src="https://github.com/user-attachments/assets/af053964-d292-457d-90d2-3bea2a83cafd">

I haven't checked yet, but I suspect the last time when the PR #812  was merged, it might not have published the docs until a release was created.
