### ISSUE TITLE
Breaking changes proposals for GitLabForm 2.*

### ISSUE THREAD

**Issue by gdubicki** [gitlabform/gitlabform#82]
As explained in [this comment](https://github.com/egnyte/gitlabform/issues/27#issuecomment-581022446) we plan to uptick GitLabForm major version to 2 because we will change the config syntax.

We will do that together for #27 and #68 but while doing that we can also improve config syntax in some other ways that are not possible in v. 1 as they would be backward incompatible.

And we can also consider other changes, which would be breaking ones.

Everyone is welcome to share your opinions and ideas. :) I am pinging some specific people as recently involved users / contributors, but it does not mean that we are not listening to other opinions. :)

Users active in recent issues: @weakcamel, @Dridge, @smcgregor83, @masonbivens, @ginkel ?

Contributors: @mkjmdski, @akaRem, @SilverXXX, @srkavin, @mrueg, @icy, @dom-nie, @davidarcher, @brtj, @johanfleury, @kassybas

**Comment by weakcamel** [comment]
The only other part of syntax I find slightly unclear and potentially to be considered while bumping the major version is the configuration of groups.

Currently there are `group_settings` which are actually applicable to *projects* in a group and there are  e.g. `group_secret_variables` which are under `common_settings`.

As Gitlab seems to allow more and more options to be defined on group level (plus there is a ticket to implement instance  level settings - https://gitlab.com/gitlab-org/gitlab-foss/issues/3897), it would be clearer to distinguish that.

**Comment by rbartuzel** [comment]
Hi @gdubicki !

As I understand you are going to migrate some functionalities of GitLabForm to using a new version of API that enforce some breaking changes in configuration. 

Are you going to implement `Protected branch` in the way described here https://docs.gitlab.com/ee/api/protected_branches.html with all possible configuration options including Branch protection on user basis or it should be implemented as a separate issue like #99?

**Comment by gdubicki** [comment]
Hey @rbartuzel !

Frankly I don't currently have the time to work on big changes to GitLabForm, like 2.0. So if anyone wants more of `Protected branches API` features it would be best to create PRs for specific things.

**Comment by glensc** [comment]
If the breaking change is format of the config file, please include a converter! :)

**Comment by gdubicki** [comment]
I have developed a proposal of a config syntax for v2.

It splits group configs from the projects configs to avoid ambiguity that @weakcamel has mentioned above (But btw: `group_settings` ARE settings for the group as they operate on the API for groups, not projects - https://docs.gitlab.com/ee/api/groups.html . However by the nature of the group which is a container for projects, effectively they do apply mostly to projects within it.).

Thanks to that split we can introduce new selectors for the configuration of groups and projects, including personal ones (#106). This will allow choosing groups and projects by using regexp patterns (which is a feature that there is no ticket for, but that we would benefit from it at Egnyte).

Please check out https://github.com/egnyte/gitlabform/pull/138 and share your opinions. :)

**Comment by gdubicki** [comment]
I have just pushed an updated proposal of the config syntax. 😅 As I have tried using the splitted version in practice (for Egnyte's config) it turned out that strict separation of groups and projects makes configuration that relates to the same things split into 2 possibly distant configuration fragments. The reason for that is exactly the fact that I mentioned above - groups are basically containers for projects...

So please check out the updated config example in #138. ;)

**Comment by amimas** [comment]
@gdubicki   - Should this be closed?
