### ISSUE TITLE
Saml group links fails to update when links exists 

### ISSUE THREAD

**Issue by ItsJustMagic** [gitlabform/gitlabform#823]
**Describe the bug**

When applying the following config
```
projects_and_groups:
  "*":
    saml_group_links: 
      devops_are_maintainers: 
        saml_group_name: devops
        access_level: maintainer
      developers_are_developers:
        saml_group_name: developers
        access_level: developer
      enforce: true
``` 

I get the error 

```
>>> Getting requested groups or projects...
:: # of groups to process: 1
:: # of projects to process: 0
@ (1/1) Processing group: mygroupname
Warning: Error occurred while processing group mygroupname, exception:
'name'
:: # of groups processed successfully: 0
:: # of projects processed successfully: 0
:: # of groups failed: 1
:: Failed group 1: mygroupname
```

However when I remove all the group links from my group, it runs successfully. 

This only fails when there are existing saml links. 

**GitLabForm version**

3.14.1

**GitLab version**

17.4.0-pre

**Comment by infame-io** [comment]
OMG. Thank you for fixing this @ItsJustMagic I was having the same issue. Legend!!!!

**Comment by ItsJustMagic** [comment]
@amimas @TimKnight-DWP?

**Comment by TimKnight-DWP** [comment]
@ItsJustMagic saml links are one of those which are only available with Ultimate right? Which suggests we probably don't have tests for them - please feel free to at least raise an MR adding an integration test for these. Logic is probably just missing somewhere 👍

**Comment by ItsJustMagic** [comment]
@TimKnight-DWP this is my attempt on fixing this issue https://github.com/gitlabform/gitlabform/pull/824
Let me know if I'm missing anything

**Comment by TimKnight-DWP** [comment]
@ItsJustMagic thanks I'll give it a review

**Comment by ItsJustMagic** [comment]
thanks mate, appreciated
