### ISSUE TITLE
Allow for Custom Naming of Approval Groups

### ISSUE THREAD

**Issue by masonbivens** [gitlabform/gitlabform#95]
There are times where being able to specifically name Approval Groups to a certain name would be beneficial. The one that directly comes to mind would be related to the [Vulnerability-Check](https://docs.gitlab.com/ee/user/application_security/index.html#security-approvals-in-merge-requests)

I know there is still some finicky behavior around the Approval Group API #90 but would still be a handy addition.

**Comment by gdubicki** [comment]
Hi @masonbivens , thanks for the idea! We are open to accept PR to make the current approval group configurable OR add more approval groups. However for the latter we would need a Premium license / Silver account at gitlab.com for testing.

**Comment by masonbivens** [comment]
@gdubicki  I reached out to our account rep about the posibility of getting licensing and they pointed me here - [Gitlab Open Source Program](https://about.gitlab.com/solutions/open-source/program/). I'm not sure if you guys have taken a look at this already, but the project at a glance appears to meet the necessary criteria for the free licensing

**Comment by gdubicki** [comment]
Cool, I’ll try to do that!

**Comment by gdubicki** [comment]
Sorry, I am not sure why the commit shown above this comment says that that release contain a fix for this issue - ti didn't.

Custom naming for Approval Groups is not possible as of now.

**Comment by yashwanth-l** [comment]
any timeline on when this feature would be available with gitlabform?

**Comment by gdubicki** [comment]
Yes, it will be, @yashwanth-l.

**Comment by gdubicki** [comment]
[v3.4.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.4.0) with this feature has finally been released as a new stable release. 🥳

The docs are available at https://gitlabform.github.io/gitlabform/reference/merge_requests/.

Please open new issues if you find any bugs in the new features.
